package org.iets3.ears.gxw.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private final ConceptPresentation props_AbstractEventDrivenReq = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_AbstractUbiquitousReq = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_AbstractedUnwantedReq = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_AndFormulaSR = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_AndFormulaTr = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_AtomicFormulaSR = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_AtomicFormulaTr = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Axiom = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_BinaryFormulaSR = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_BinaryFormulaTr = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_ComplexEventDrivenReq = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_ComplexEventDrivenUntil = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_GlossaryChunk = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Happens = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_HappensStable = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_NormalEventDrivenOptionalFeatReq = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_NormalEventDrivenReq = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_NormalRisingEdgeReq = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_NormalUbiquitousReq = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_NotFormulaSR = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_NotFormulaTr = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Occurs = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_OrFormulaSR = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_OrFormulaTr = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_PropositionalFormulaSR = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_PropositionalFormulaTr = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_RequirementChunk = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_RequirementTemplate = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_SystemName = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_SystemResponse = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Trigger = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_TriggerModifier = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_UnaryFormulaSR = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_UnaryFormulaTr = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_UnwantedReq = new ConceptPresentationBuilder().create();

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case 0:
        return props_AbstractEventDrivenReq;
      case 1:
        return props_AbstractUbiquitousReq;
      case 2:
        return props_AbstractedUnwantedReq;
      case 3:
        return props_AndFormulaSR;
      case 4:
        return props_AndFormulaTr;
      case 5:
        return props_AtomicFormulaSR;
      case 6:
        return props_AtomicFormulaTr;
      case 7:
        return props_Axiom;
      case 8:
        return props_BinaryFormulaSR;
      case 9:
        return props_BinaryFormulaTr;
      case 10:
        return props_ComplexEventDrivenReq;
      case 11:
        return props_ComplexEventDrivenUntil;
      case 12:
        return props_GlossaryChunk;
      case 13:
        return props_Happens;
      case 14:
        return props_HappensStable;
      case 15:
        return props_NormalEventDrivenOptionalFeatReq;
      case 16:
        return props_NormalEventDrivenReq;
      case 17:
        return props_NormalRisingEdgeReq;
      case 18:
        return props_NormalUbiquitousReq;
      case 19:
        return props_NotFormulaSR;
      case 20:
        return props_NotFormulaTr;
      case 21:
        return props_Occurs;
      case 22:
        return props_OrFormulaSR;
      case 23:
        return props_OrFormulaTr;
      case 24:
        return props_PropositionalFormulaSR;
      case 25:
        return props_PropositionalFormulaTr;
      case 26:
        return props_RequirementChunk;
      case 27:
        return props_RequirementTemplate;
      case 28:
        return props_SystemName;
      case 29:
        return props_SystemResponse;
      case 30:
        return props_Trigger;
      case 31:
        return props_TriggerModifier;
      case 32:
        return props_UnaryFormulaSR;
      case 33:
        return props_UnaryFormulaTr;
      case 34:
        return props_UnwantedReq;
    }
    throw new IllegalStateException("Unknown concept " + c);
  }
}
