package org.iets3.ears.gxw.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.IconResource;

public class IconContainer {
  protected static IconResource RESOURCE_a0a0m = new IconResource("GxwGlossary1.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a0ab = new IconResource("GXW-Req.png", IconContainer.class);
}
