package org.iets3.ears.gxw.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class RequirementTemplate_Constraints extends BaseConstraintsDescriptor {
  public RequirementTemplate_Constraints() {
    super(MetaAdapterFactory.getInterfaceConcept(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x6979ba361f3d77d3L, "org.iets3.ears.gxw.structure.RequirementTemplate"));
  }

}
