package org.iets3.ears.gxw.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.BehaviorRegistry;
import jetbrains.mps.smodel.language.ConceptRegistry;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.SModifiersImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import java.util.Map;
import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.MapSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;

public final class PropositionalFormulaTr__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getInterfaceConcept(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x333c641fcaa983a5L, "org.iets3.ears.gxw.structure.PropositionalFormulaTr");
  private static final BehaviorRegistry REGISTRY = ConceptRegistry.getInstance().getBehaviorRegistry();

  public static final SMethod<String> toFormulaString_id3cWp1ZaFwJv = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("toFormulaString").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("3cWp1ZaFwJv").registry(REGISTRY).build(SMethodBuilder.createJavaParameter((Class<Map<SNode, String>>) ((Class) Object.class), ""));
  public static final SMethod<String> toTextString_id3cWp1ZaFwKU = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("toTextString").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("3cWp1ZaFwKU").registry(REGISTRY).build();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(toFormulaString_id3cWp1ZaFwJv, toTextString_id3cWp1ZaFwKU);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static String toFormulaString_id3cWp1ZaFwJv(@NotNull SNode __thisNode__, Map<SNode, String> triggerMap) {
    if (SNodeOperations.isInstanceOf(__thisNode__, MetaAdapterFactory.getConcept(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x333c641fcaa9839fL, "org.iets3.ears.gxw.structure.AtomicFormulaTr"))) {
      return MapSequence.fromMap(triggerMap).get(SLinkOperations.getTarget(SNodeOperations.cast(__thisNode__, MetaAdapterFactory.getConcept(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x333c641fcaa9839fL, "org.iets3.ears.gxw.structure.AtomicFormulaTr")), MetaAdapterFactory.getReferenceLink(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x333c641fcaa9839fL, 0x333c641fcaa983b7L, "atom")));
    } else if (SNodeOperations.isInstanceOf(__thisNode__, MetaAdapterFactory.getConcept(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x333c641fcaa983a1L, "org.iets3.ears.gxw.structure.NotFormulaTr"))) {
      return "!" + PropositionalFormulaTr__BehaviorDescriptor.toFormulaString_id3cWp1ZaFwJv.invoke(SLinkOperations.getTarget(SNodeOperations.cast(__thisNode__, MetaAdapterFactory.getConcept(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x333c641fcaa983a1L, "org.iets3.ears.gxw.structure.NotFormulaTr")), MetaAdapterFactory.getContainmentLink(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x333c641fcaa983a8L, 0x333c641fcaa983afL, "arg")), triggerMap);
    } else if (SNodeOperations.isInstanceOf(__thisNode__, MetaAdapterFactory.getConcept(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x333c641fcaa9839eL, "org.iets3.ears.gxw.structure.AndFormulaTr"))) {
      return "(" + PropositionalFormulaTr__BehaviorDescriptor.toFormulaString_id3cWp1ZaFwJv.invoke(SLinkOperations.getTarget(SNodeOperations.cast(__thisNode__, MetaAdapterFactory.getConcept(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x333c641fcaa9839eL, "org.iets3.ears.gxw.structure.AndFormulaTr")), MetaAdapterFactory.getContainmentLink(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x333c641fcaa983a7L, 0x333c641fcaa983a9L, "arg1")), triggerMap) + " && " + PropositionalFormulaTr__BehaviorDescriptor.toFormulaString_id3cWp1ZaFwJv.invoke(SLinkOperations.getTarget(SNodeOperations.cast(__thisNode__, MetaAdapterFactory.getConcept(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x333c641fcaa9839eL, "org.iets3.ears.gxw.structure.AndFormulaTr")), MetaAdapterFactory.getContainmentLink(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x333c641fcaa983a7L, 0x333c641fcaa983aaL, "arg2")), triggerMap) + ")";
    } else {
      return "(" + PropositionalFormulaTr__BehaviorDescriptor.toFormulaString_id3cWp1ZaFwJv.invoke(SLinkOperations.getTarget(SNodeOperations.cast(__thisNode__, MetaAdapterFactory.getConcept(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x333c641fcaa983a2L, "org.iets3.ears.gxw.structure.OrFormulaTr")), MetaAdapterFactory.getContainmentLink(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x333c641fcaa983a7L, 0x333c641fcaa983a9L, "arg1")), triggerMap) + " || " + PropositionalFormulaTr__BehaviorDescriptor.toFormulaString_id3cWp1ZaFwJv.invoke(SLinkOperations.getTarget(SNodeOperations.cast(__thisNode__, MetaAdapterFactory.getConcept(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x333c641fcaa983a2L, "org.iets3.ears.gxw.structure.OrFormulaTr")), MetaAdapterFactory.getContainmentLink(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x333c641fcaa983a7L, 0x333c641fcaa983aaL, "arg2")), triggerMap) + ")";
    }

  }
  /*package*/ static String toTextString_id3cWp1ZaFwKU(@NotNull SNode __thisNode__) {
    if (SNodeOperations.isInstanceOf(__thisNode__, MetaAdapterFactory.getConcept(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x333c641fcaa9839fL, "org.iets3.ears.gxw.structure.AtomicFormulaTr"))) {
      return SPropertyOperations.getString(SLinkOperations.getTarget(SNodeOperations.cast(__thisNode__, MetaAdapterFactory.getConcept(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x333c641fcaa9839fL, "org.iets3.ears.gxw.structure.AtomicFormulaTr")), MetaAdapterFactory.getReferenceLink(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x333c641fcaa9839fL, 0x333c641fcaa983b7L, "atom")), MetaAdapterFactory.getProperty(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0xe98cc5716ef655aL, 0x5d97a5a8692a5e10L, "text"));
    } else if (SNodeOperations.isInstanceOf(__thisNode__, MetaAdapterFactory.getConcept(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x333c641fcaa983a1L, "org.iets3.ears.gxw.structure.NotFormulaTr"))) {
      return "not " + PropositionalFormulaTr__BehaviorDescriptor.toTextString_id3cWp1ZaFwKU.invoke(SLinkOperations.getTarget(SNodeOperations.cast(__thisNode__, MetaAdapterFactory.getConcept(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x333c641fcaa983a1L, "org.iets3.ears.gxw.structure.NotFormulaTr")), MetaAdapterFactory.getContainmentLink(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x333c641fcaa983a8L, 0x333c641fcaa983afL, "arg")));
    } else if (SNodeOperations.isInstanceOf(__thisNode__, MetaAdapterFactory.getConcept(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x333c641fcaa9839eL, "org.iets3.ears.gxw.structure.AndFormulaTr"))) {
      return PropositionalFormulaTr__BehaviorDescriptor.toTextString_id3cWp1ZaFwKU.invoke(SLinkOperations.getTarget(SNodeOperations.cast(__thisNode__, MetaAdapterFactory.getConcept(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x333c641fcaa9839eL, "org.iets3.ears.gxw.structure.AndFormulaTr")), MetaAdapterFactory.getContainmentLink(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x333c641fcaa983a7L, 0x333c641fcaa983a9L, "arg1"))) + " and " + PropositionalFormulaTr__BehaviorDescriptor.toTextString_id3cWp1ZaFwKU.invoke(SLinkOperations.getTarget(SNodeOperations.cast(__thisNode__, MetaAdapterFactory.getConcept(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x333c641fcaa9839eL, "org.iets3.ears.gxw.structure.AndFormulaTr")), MetaAdapterFactory.getContainmentLink(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x333c641fcaa983a7L, 0x333c641fcaa983aaL, "arg2")));
    } else {
      return PropositionalFormulaTr__BehaviorDescriptor.toTextString_id3cWp1ZaFwKU.invoke(SLinkOperations.getTarget(SNodeOperations.cast(__thisNode__, MetaAdapterFactory.getConcept(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x333c641fcaa983a2L, "org.iets3.ears.gxw.structure.OrFormulaTr")), MetaAdapterFactory.getContainmentLink(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x333c641fcaa983a7L, 0x333c641fcaa983a9L, "arg1"))) + " or " + PropositionalFormulaTr__BehaviorDescriptor.toTextString_id3cWp1ZaFwKU.invoke(SLinkOperations.getTarget(SNodeOperations.cast(__thisNode__, MetaAdapterFactory.getConcept(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x333c641fcaa983a2L, "org.iets3.ears.gxw.structure.OrFormulaTr")), MetaAdapterFactory.getContainmentLink(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x333c641fcaa983a7L, 0x333c641fcaa983aaL, "arg2")));
    }
  }

  /*package*/ PropositionalFormulaTr__BehaviorDescriptor() {
    super(REGISTRY);
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((String) toFormulaString_id3cWp1ZaFwJv(node, (Map<SNode, String>) parameters[0]));
      case 1:
        return (T) ((String) toTextString_id3cWp1ZaFwKU(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }
}
